all:
	gcc -I. `net-snmp-config --cflags`   -c -o assignment2.o assignment2.c
	gcc -o assignment2 assignment2.o ipcheck.c io_controller.c `net-snmp-config --libs`
	./assignment2

clean:
	rm ./assignment2 assignment2.o